name: Test ksync
on:
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Test Tools
        run: |
          pip install .[test]

      - name: Run Pytest
        run: pytest
